- name: Install flatpaks from flathub
  community.general.flatpak:
    name:
      - chat.simplex.simplex # SimpleX Chat
      - com.github.Anuken.Mindustry # Mindustry
      - com.github.wwmm.easyeffects # Easy Effects
      - com.heroicgameslauncher.hgl # Heroic Games Launcher
      - com.obsproject.Studio # OBS Studio
      - dev.vencord.Vesktop # Vesktop
      - io.mpv.Mpv # mpv
      - md.obsidian.Obsidian # Obsidian
      - org.gimp.GIMP # GIMP
      - org.inkscape.Inkscape # Inkscape
      - org.kartkrew.RingRacers # Ring Racers
      - org.kde.kdenlive # Kdenlive
      - org.keepassxc.KeePassXC # KeePassXC
      - org.localsend.localsend_app # LocalSend
      - org.mozilla.Thunderbird # Thunderbird
      - org.prismlauncher.PrismLauncher # Prism Launcher
      - org.signal.Signal # Signal Desktop
      - sh.ppy.osu # osu!
      - app/org.wesnoth.Wesnoth/x86_64/stable # Battle for Wesnoth
      - com.shatteredpixel.shatteredpixeldungeon # Shattered Pixel Dungeon
      - io.github.picocrypt.Picocrypt # Picocrypt
      - com.calibre_ebook.calibre # calibre
      - net.openra.OpenRA # openRA
      - com.github.neithern.g4music # Gapless
